### ISSUE TITLE
Deciding the general structure of our mongoDB, creating initial database.

### ISSUE THREAD

**Issue by s1846118** [CodeDaddy69/not-a-frontend-app#1]
We need to decide the attributes in out database before I can start on the python scrips which can perform CRUD functionality. Once we have decided this we then must: 

- Remove the direct link from React to MongoDB as it is no longer needed (we access through Pythons mongoDB api). 
- Create an example DB which is required to go ahead and build the Python functionality.
- After this we can then look at how we can integrate the front end to communicate with Python to call functions and send/receive data.

**Comment by CodeDaddy69** [comment]
Basic Data we need:

- Store listings 
      - Store escrow state data (maybe in lisitings db maybe seperate)
- Store account stats

anymore??
