### ISSUE TITLE
Only show relevant endpoints when logged in (i.e buy now and accounts page)

### ISSUE THREAD

**Issue by CodeDaddy69** [CodeDaddy69/not-a-frontend-app#4]
- Change the react to only show account stats once logged in
- Change the buy button on listings to only show if logged in

**Comment by s1846118** [comment]
This issue falls under the whole cookies and Phantom wallet authentication thing right? I will open another issue with that as the header?

**Comment by CodeDaddy69** [comment]
sounds good il close this
